module.exports = {
    playerAndVideoControls: $('#player, .video-controls'),
    player: $('#player'),
    videoControls: $('.video-controls'),
    playPauseButton: $('.pp-button'),
    playButton: $("#play-button"),
    pauseButton: $("#pause-button"),
    fullscrean: $('.fullscrean'),
    stepPrevious: $('.step-previous'),
    stepNext: $('.step-next'),
    slider: $('.slider'),
    pinButton: $('#pin-button'),
    skipButton: $('.skip-button'),
    next: $('.next'),
    previous: $('.previous'),
    timerText: $('.timer>span'),
    pinText: $('#pin-button>span'),
    skipMenu: $('#skip-menu'),
    sound: $('.sound'),
    sliderSound: $('.slider-sound'),
    playList: $('#play-list'),
    sideMenu: $('.side-menu'),
}